"""Comentario del cambio

Revision ID: 6a783d4c1bb9
Revises: d3fc2507de5f
Create Date: 2025-03-05 19:39:39.398091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a783d4c1bb9'
down_revision = 'd3fc2507de5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la oferta'),
    sa.Column('username', sa.String(length=80), nullable=True, comment='Nombre de usuario'),
    sa.Column('lastname', sa.String(length=80), nullable=True, comment='Apellido del usuario'),
    sa.Column('usermail', sa.String(length=120), nullable=False, comment='Correo electrónico del usuario'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='Contraseña del usuario'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usermail')
    )
    op.drop_table('recommender_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommender_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Identificador único de la oferta'),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True, comment='Nombre de usuario'),
    sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=True, comment='Apellido del usuario'),
    sa.Column('usermail', sa.VARCHAR(length=120), autoincrement=False, nullable=False, comment='Correo electrónico del usuario'),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='Contraseña del usuario'),
    sa.PrimaryKeyConstraint('id', name='recommender_users_pkey'),
    sa.UniqueConstraint('usermail', name='recommender_users_usermail_key')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
