"""Initial migration

Revision ID: d3fc2507de5f
Revises: 
Create Date: 2025-03-05 19:36:41.835541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fc2507de5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommender_users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la oferta'),
    sa.Column('username', sa.String(length=80), nullable=True, comment='Nombre de usuario'),
    sa.Column('lastname', sa.String(length=80), nullable=True, comment='Apellido del usuario'),
    sa.Column('usermail', sa.String(length=120), nullable=False, comment='Correo electrónico del usuario'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='Contraseña del usuario'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usermail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommender_users')
    # ### end Alembic commands ###
