"""Initial migration

Revision ID: fde9862a03aa
Revises: 
Create Date: 2025-03-05 22:33:01.587390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde9862a03aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la oferta'),
    sa.Column('username', sa.String(length=80), nullable=True, comment='Nombre de usuario'),
    sa.Column('lastname', sa.String(length=80), nullable=True, comment='Apellido del usuario'),
    sa.Column('usermail', sa.String(length=120), nullable=False, comment='Correo electrónico del usuario'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='Contraseña del usuario'),
    sa.Column('role', sa.Enum('paciente', 'doctor', name='roleenum'), nullable=False, comment='Rol del usuario (paciente o doctor)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usermail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
